### ISSUE TITLE
Public previews not working when uploading html posts via admin api

### ISSUE THREAD

**Issue by mhelf** [TryGhost/Koenig#267]
Hi I found a possible bug,

when you fetch a post and reupload it via the admin ui the public preview is gone.

Steps to reproduce:
1. Add a post via ghost admin ui
2. Add a public preview / members only card to that post
3. Fetch that post with admin api
4. Observe the fetched html it contains a comment `<!--members-only-->` indicating the public preview, the mobiledoc content contains a paywall-card.
5. Reupload the post with source html
6. The public preview is gone you can't see it anymore in the ghost editor.

Please also see:
https://forum.ghost.org/t/public-previews-via-html-admin-api-publish/25468

**Comment by rankerpost** [comment]
Is there a way to have markdown/html recognise the code `<!--members-only-->` so that it adds the paywall without breaking the markdown text in two using the UI?

**Comment by kevinansfield** [comment]
A parser for converting `<!--members-only-->` to a paywall card was implemented in our switch to a new editor framework so this issue is resolved.

> Is there a way to have markdown/html recognise the code  so that it adds the paywall without breaking the markdown text in two using the UI?

That's already the case, if you add the `<!--members-only-->` comment inside an HTML card or markdown card (needs to be surrounded by blank lines) then it will work the same as adding a paywall card in the main editor.
